# Generated by Django 5.1.7 on 2025-03-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobentity',
            table=None,
        ),
    ]
