# Generated by Django 5.1.7 on 2025-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0002_alter_jobentity_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
