# Generated by Django 5.1.7 on 2025-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0003_jobentity_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(unique=True)),
                ('experience', models.TextField()),
                ('education', models.CharField(choices=[('Associate degree', 'Associate degree'), ('Bachelors degree', 'Bachelors degree'), ('Masters degree', 'Masters degree'), ('Doctoral degree', 'Doctoral degree')], max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
