# Generated by Django 5.1.7 on 2025-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0004_userentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentity',
            name='phone_number',
            field=models.CharField(unique=True),
        ),
    ]
