# Generated by Django 5.1.7 on 2025-04-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0005_alter_userentity_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentity',
            old_name='user_name',
            new_name='username',
        ),
    ]
