# Generated by Django 5.1.7 on 2025-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0008_jobapplicationentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationentity',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
