# Generated by Django 5.1.7 on 2025-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0009_alter_jobapplicationentity_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentity',
            name='location',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
