# Generated by Django 5.1.7 on 2025-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0010_jobentity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='userentity',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
