openapi: 3.0.3
info:
  title: Job API (User + Admin)
  version: 1.0.0
  description: |
    Unified Swagger documentation for both user-facing and admin-facing endpoints.
    - User endpoints are under `/api/v1/`
    - Admin endpoints are under `/api/admin/`
servers:
  - url: http://localhost:8000

tags:
  - name: User
    description: Public and authenticated user endpoints
  - name: Admin
    description: Admin-only endpoints

paths:
  /api/v1/jobs/:
    get:
      summary: Retrieve jobs
      description: |
        Get job(s) based on optional query parameters. If no filters are applied, returns all jobs.
      parameters:
        - name: job_id
          in: query
          required: false
          schema:
            type: integer
        - name: company_name
          in: query
          required: false
          schema:
            type: string
        - name: title
          in: query
          required: false
          schema:
            type: string
        - name: requirements
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of jobs or single job
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Job'
                  - type: array
                    items:
                      $ref: '#/components/schemas/Job'
        '400':
          description: Invalid input or job not found
      tags:
        - User

  /api/v1/register/:
    post:
      summary: Authenticate user and return JWT tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Tokens returned
        '400':
          description: Invalid credentials
      tags:
        - User

  /api/v1/profile/:
    get:
      summary: Get current user's profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error fetching profile
      tags:
        - User
    patch:
      summary: Update profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Profile updated
        '400':
          description: Error updating profile
      tags:
        - User

  /api/v1/sign_up/:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
        '400':
          description: Error
      tags:
        - User

  /api/v1/job/apply/:
    get:
      summary: Get jobs user applied to
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
      tags:
        - User
    post:
      summary: Apply for a job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - job_id
              properties:
                job_id:
                  type: integer
                note:
                  type: string
                resume:
                  type: string
                  format: binary
      responses:
        '201':
          description: Applied successfully
        '400':
          description: Application failed
      tags:
        - User

  /api/admin/job/:
    get:
      summary: Admin - Get or query job(s)
      security:
        - bearerAuth: []
      parameters:
        - name: job_id
          in: query
          required: false
          schema:
            type: integer
        - name: company_name
          in: query
          required: false
          schema:
            type: string
        - name: title
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Job(s) found
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Job'
                  - type: array
                    items:
                      $ref: '#/components/schemas/Job'
      tags:
        - Admin
    post:
      summary: Admin - Create a job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobInput'
      responses:
        '201':
          description: Job created
        '400':
          description: Error
      tags:
        - Admin
    patch:
      summary: Admin - Update a job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/JobInput'
                - type: object
                  required: [id]
                  properties:
                    id:
                      type: integer
      responses:
        '201':
          description: Job updated
        '400':
          description: Error
      tags:
        - Admin
    delete:
      summary: Admin - Delete a job
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Job deleted
        '400':
          description: Error
      tags:
        - Admin

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Job:
      type: object
      properties:
        id:
          type: integer
        company_name:
          type: string
        title:
          type: string
        location:
          type: string
        agreement:
          type: string
          enum: [full_time, part_time, remote]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        salary:
          type: integer
        description:
          type: string
        requirements:
          type: string
        is_available:
          type: boolean

    JobInput:
      type: object
      properties:
        company_name:
          type: string
        title:
          type: string
        location:
          type: string
        agreement:
          type: string
        salary:
          type: integer
        requirements:
          type: string
        description:
          type: string
        is_available:
          type: boolean

    User:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone_number:
          type: string
        experience:
          type: string
        education:
          type: string
          enum:
            - Associate degree
            - Bachelors degree
            - Masters degree
            - Doctoral degree